
title: My Resume
url: 'www.lmtowner.com'
baseurl:  #'change it according to your repository name



# Profile information
yourname: La-Keisha M. Towner  ## put your name
title: 'Web Developer &amp; Native Mobile App Developer'  ## your title
location: New York, NY


## Social Profiles
linkedin: https://www.linkedin.com/in/lmtowner  ## your linkedin account url
githhub: https://www.github.com/LM-Towner
## facebook: https://www.facebook.com/QuietLTStorm
## twitter: https://www.twitter.com/LMT_Developer



# Update all the sections by editing the files inside _includes folder.

# theme: jekyll-theme-hacker
